### ISSUE TITLE
jittor文件夹

### ISSUE THREAD

**Issue by wm-Githuber** [PengtaoJiang/LayerCAM#10]
姜博士您好，在您 layercam.py文件中包含了多个 jittor 库文件，请问这个库文件是您存放环境库的文件夹吗

**Comment by PengtaoJiang** [comment]
根目录是pytorch代码，在pytorch环境下跑，```LayerCAM-jittor/```文件夹下是jittor code版本，在jittor环境下跑。

**Comment by wm-Githuber** [comment]
好的，谢谢您
