### ISSUE TITLE
实验结果差

### ISSUE THREAD

**Issue by jerehrong** [PengtaoJiang/LayerCAM#11]
姜博士，我想请问一下我用这个命令跑出来的效果非常差是因为什么。python test.py --img_path=images/ILSVRC2012_val_00000073.JPEG
我的环境配置是py3.8.1,pytorch=1.4.0,torchvision=0.5.0.
![stage_5](https://github.com/PengtaoJiang/LayerCAM-jittor/assets/144826410/45ddea9c-9081-4b3d-8012-f59cf5db7ec0)

**Comment by PengtaoJiang** [comment]
你好，根据你提供的信息，很难定位到你的问题在哪里，可以提供更多的信息吗？

**Comment by jerehrong** [comment]
我是下载完代码以后直接用你在readme.md文件中的代码运行的。我自己没有训练过的模型，你这个代码是需要在已经训练过的模型下运行吗？







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月19日(星期五) 下午2:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PengtaoJiang/LayerCAM-jittor] 实验结果差 (Issue #11)














 
你好，根据你提供的信息，很难定位到你的问题在哪里，可以提供更多的信息吗？

**Comment by PengtaoJiang** [comment]
我们下载下来代码重新运行了下，结果正常，环境是torch=1.10.0 torchvision=0.11.0。
![1](https://github.com/PengtaoJiang/LayerCAM-jittor/assets/23328456/6a95a4ce-e7c4-413e-9870-12d786520f1b) ![2](https://github.com/PengtaoJiang/LayerCAM-jittor/assets/23328456/81344e7e-9e5b-4630-8b15-3669a3872df5) ![3](https://github.com/PengtaoJiang/LayerCAM-jittor/assets/23328456/2eafd278-5dda-4814-bba8-0e58b02d4006) ![4](https://github.com/PengtaoJiang/LayerCAM-jittor/assets/23328456/d33039cb-e83c-474d-a24d-8fdd8d03a5b2) ![5](https://github.com/PengtaoJiang/LayerCAM-jittor/assets/23328456/79f31105-45d3-494f-8326-b4f1664d50af)

**Comment by jerehrong** [comment]
感谢你的解答，问题已经解决在你发的环境下运行效果跟你们的一直

**Comment by jerehrong** [comment]
感谢回答，问题已经解决
