### ISSUE TITLE
公式(8)

### ISSUE THREAD

**Issue by Buildernet** [PengtaoJiang/LayerCAM#3]
你好  请问图片中我标注的A是相同的吗，为什么k的位置不一样，如果不是同一个，请问有什么区别嘛。

![图片](https://user-images.githubusercontent.com/41811026/132946594-cd8761c6-bdf4-4754-ab2b-fc4811510e10.png)

**Comment by PengtaoJiang** [comment]
Sorry for the typos. It's the same variable. Thanks for your advice.

**Comment by PengtaoJiang** [comment]
抱歉，我写错了， 这是同一个变量。 感谢您的指正！
